=== ANGELATOP/AngelaJavaProjectMaMWS/AngelaJavaProjectMaMWS/src/common/split/subflow/itemUpdate/2026-02-07 itemUpdate.schema_worked.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"ProfileId": {
			"type": "string"
		},
		"CreatedTimestamp": {
			"type": "string"
		},
		"RetailPrice": {
			"type": "string"
		},
		"AttributeGroupId": {
			"type": "string"
		},
		"ShelfDays": {
			"type": "number"
		},
		"OriginalAverageWeight": {
			"type": "number"
		},
		"TrackCountryOfOrigin": {
			"type": "number"
		},
		"ShortDescription": {
			"type": "string"
		},
		"CurrencyCode": {
			"type": "string"
		},
		"ProducerOfGoodsId": {
			"type": "string"
		},
		"UpdatedBy": {
			"type": "string"
		},
		"OriginalWeight": {
			"type": "number"
		},
		"WeightOveragePercentage": {
			"type": "number"
		},
		"MaximumReceiveToExpireDays": {
			"type": "number"
		},
		"ExportLicenseNumber": {
			"type": "string"
		},
		"TiersPerPallet": {
			"type": "number"
		},
		"Hazmat": {
			"type": "number"
		},
		"Width": {
			"type": "number"
		},
		"UpdatedTimestamp": {
			"type": "string"
		},
		"Length": {
			"type": "number"
		},
		"Process": {
			"type": "string"
		},
		"ItemId": {
			"type": "string"
		},
		"LpnPerTier": {
			"type": "number"
		},
		"Height": {
			"type": "number"
		},
		"PK": {
			"type": "string"
		},
		"Unique_Identifier": {
			"type": "string"
		}
	},
	"required": [
		"ProfileId",
		"CreatedTimestamp",
		"RetailPrice",
		"AttributeGroupId",
		"ShelfDays",
		"OriginalAverageWeight",
		"TrackCountryOfOrigin",
		"ShortDescription",
		"CurrencyCode",
		"ProducerOfGoodsId",
		"UpdatedBy",
		"OriginalWeight",
		"WeightOveragePercentage",
		"MaximumReceiveToExpireDays",
		"ExportLicenseNumber",
		"TiersPerPallet",
		"Hazmat",
		"Width",
		"UpdatedTimestamp",
		"Length",
		"Process",
		"ItemId",
		"LpnPerTier",
		"Height",
		"PK",
		"Unique_Identifier"
	]
}

=== ANGELATOP/AngelaJavaProjectMaMWS/AngelaJavaProjectMaMWS/src/common/split/subflow/itemUpdate/2026-02-07 manhattanMsg_justUsedElements_worked.json
{
	"ProfileId": "KC",
	"CreatedTimestamp": "2026-01-19T16:38:10.598",
	"RetailPrice": "test",

	"AttributeGroupId": "",
	"ShelfDays": 30,
	"OriginalAverageWeight": 14.0,
	"TrackCountryOfOrigin": 2,
	"ShortDescription": "0010689 SWP CC BTR PECN DNSH 16OZ",

	"CurrencyCode": "test",
	"ProducerOfGoodsId": "test",
	"UpdatedBy": "sapintegrationadmin@awginc.com",
	"OriginalWeight": 14.0,
	"WeightOveragePercentage": 20.0,
	"MaximumReceiveToExpireDays": 365,
	"ExportLicenseNumber": "test",
	"TiersPerPallet": 6,
	"Hazmat": 2,
	"Width": 10.3,
	"UpdatedTimestamp": "2026-02-06T22:56:36.848",
	"Length": 20.1,
	"Process": "SaveBulkItemFacilities",
	"ItemId": "0010689",
	"LpnPerTier": 8,
	"Height": 10.5,
	"PK": "7688406905984381301",
	"Unique_Identifier": "7688406905984381301__0010689"
}
