=== ANGELATOP/AngelaJavaProjectMaMWS/AngelaJavaProjectMaMWS/src/commonLib/schema/GoogleAndCommonAttributes-NEW.schema2.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"googleMsgID": {
			"type": "string"
		},
		"ContextInformation": {
			"type": "object",
			"properties": {
				"Messages": {
					"type": "object",
					"properties": {
					},
					"required": [
					]
				},
				"Organization": {
					"type": "string"
				},
				"UserId": {
					"type": "string"
				},
				"UserLocale": {
					"type": "string"
				},
				"Location": {
					"type": "string"
				}
			},
			"required": [
				"Messages",
				"Organization",
				"UserId",
				"UserLocale",
				"Location"
			]
		},
		"CurrentPage": {
			"type": "number"
		},
		"ExportDocuments": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"Messages": {
						"type": "object",
						"properties": {
						},
						"required": [
						]
					},
					"PIXSpecification": {
						"type": "string"
					},
					"Description": {
						"type": "string"
					},
					"SourceTransactionType": {
						"type": "string"
					},
					"SourceEventName": {
						"type": "string"
					},
					"PIXFields": {
						"type": "object",
						"properties": {
							"AsnId": {
								"type": "string"
							}
						},
						"required": [
							"AsnId"
						]
					},
					"ItemDefinition": {
						"type": "object",
						"properties": {
							"ItemId": {
								"type": "string"
							}
						},
						"required": [
							"ItemId"
						]
					},
					"TransactionNumber": {
						"type": "string"
					},
					"SequenceNumber": {
						"type": "number"
					},
					"TransactionDateTime": {
						"type": "string"
					},
					"Organization": {
						"type": "string"
					},
					"Facility": {
						"type": "string"
					}
				},
				"required": [
					"Messages",
					"PIXSpecification",
					"Description",
					"SourceTransactionType",
					"SourceEventName",
					"PIXFields",
					"ItemDefinition",
					"TransactionNumber",
					"SequenceNumber",
					"TransactionDateTime",
					"Organization",
					"Facility"
				]
			}
		},
		"UniqueJobId": {
			"type": "string"
		},
		"TotalPages": {
			"type": "number"
		}
	},
	"required": [
		"googleMsgID",
		"ContextInformation",
		"CurrentPage",
		"ExportDocuments",
		"UniqueJobId",
		"TotalPages"
	]
}

=== ANGELATOP/AngelaJavaProjectMaMWS/AngelaJavaProjectMaMWS/src/aa/aa/sampleGoogleAndCommonAttributes.json
{
	"googleMsgID": "sample string",
	"ContextInformation": {
		"Messages": {
		},
		"Organization": "sample string",
		"UserId": "sample string",
		"UserLocale": "sample string",
		"Location": "sample string"
	},
	"CurrentPage": 11,
	"ExportDocuments": [
		{
			"Messages": {
			},
			"PIXSpecification": "sample string",
			"Description": "sample string",
			"SourceTransactionType": "sample string",
			"SourceEventName": "John Doe",
			"PIXFields": {
				"AsnId": "sample string",
				"Asn": "sample string",
				"InventoryAdjustmentType": "sample string"
			},
			"ItemDefinition": {
				"ItemId": "sample string"
			},
			"TransactionNumber": "sample string",
			"SequenceNumber": 11,
			"TransactionDateTime": "sample string",
			"Organization": "sample string",
			"Facility": "sample string"
		},
		{
			"Messages": {
			},
			"PIXSpecification": "sample string",
			"Description": "sample string",
			"SourceTransactionType": "sample string",
			"SourceEventName": "John Doe",
			"PIXFields": {
				"AsnId": "sample string",
				"Asn": "sample string",
				"InventoryAdjustmentType": "sample string"
			},
			"ItemDefinition": {
				"ItemId": "sample string"
			},
			"TransactionNumber": "sample string",
			"SequenceNumber": 11,
			"TransactionDateTime": "sample string",
			"Organization": "sample string",
			"Facility": "sample string"
		}
	],
	"UniqueJobId": "sample string",
	"TotalPages": 11
}
